export const animeData = [
    {
        title: "Why Raeliana Ended Up at the Duke’s Mansion",
        image: "../images/Why Raeliana Ended Up at the Duke’s Mansion.jpg",
        synopsis: "Synopsis for Anime 1",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-04T14:00:00",
        score: 8.5,
        currentEpisode: 5,
        totalEpisodes: 12,
    },
    {
        title: "The Eminence in Shadow",
        image: "../images/The Eminence in Shadow.jpg",
        synopsis: "Synopsis for Anime 1",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-04T14:00:00",
        score: 8.5,
        currentEpisode: 3,
        totalEpisodes: 20,
    },
	    {
        title: "In Another World With My Smartphone - Season 2",
        image: "../images/In Another World With My Smartphone - Season 2.jpg",
        synopsis: "Synopsis for Anime 2",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-05T12:32:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
    {
        title: "VINLAND SAGA - Season 2",
        image: "../images/VINLAND SAGA - Season 2.jpg",
        synopsis: "Synopsis for Anime 3",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-08T15:00:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 24,
    },
    {
        title: " I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too",
        image: "../images/I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: " Dead Mount Death Play",
        image: "../images/Dead Mount Death Play.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Kuma Kuma Kuma Bear - Season 2",
        image: "../images/Kuma Kuma Kuma Bear - Season 2.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Monday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Tokyo Revengers: Christmas Showdown",
        image: "../images/Tokyo Revengers Christmas Showdown.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Tuesday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 1,
        totalEpisodes: 1,
    },
	    {
        title: "Urusei Yatsura",
        image: "../images/Urusei Yatsura.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Wednesday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Sacrificial Princess and the King of Beasts",
        image: "../images/Sacrificial Princess and the King of Beasts.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Wednesday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 24,
    },
	    {
        title: "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense. Season 2",
        image: "../images/BOFURI I Don't Want to Get Hurt, so I'll Max Out My Defense Season 2.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Wednesday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "KamiKatsu: Working for God in a Godless World",
        image: "../images/KamiKatsu Working for God in a Godless World.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Wednesday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "KONOSUBA -An Explosion on This Wonderful World",
        image: "../images/KONOSUBA -An Explosion on This Wonderful World.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Wednesday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Is It Wrong to Try to Pick Up Girls in a Dungeon? | Season 4 (Cour 2)",
        image: "../images/Is It Wrong to Try to Pick Up Girls in a Dungeon Season 4 (Cour 2).jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Thursday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Dr. STONE: New World",
        image: "../images/Dr. STONE New World.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Thursday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "The Ancient Magus' Bride - Season 2",
        image: "../images/The Ancient Magus' Bride - Season 2.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Thursday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Ranking of Kings: Treasure Chest of Courage",
        image: "../images/Ranking of Kings Treasure Chest of Courage.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Thursday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "The Legendary Hero is Dead",
        image: "../images/The Legendary Hero is Dead.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Thursday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "TONIKAWA: Over the Moon For You - Season 2",
        image: "../images/TONIKAWA Over the Moon For You - Season 2.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Friday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Hell's Paradise",
        image: "../images/Hell's Paradise.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Saturday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 13,
    },
	    {
        title: "A Galaxy Next Door",
        image: "../images/A Galaxy Next Door.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Saturday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Utawarerumono Mask of Truth",
        image: "../images/Utawarerumono Mask of Truth.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "The Aristocrat's Otherworldly Adventure: Serving Gods Who Go Too Far",
        image: "../images/The Aristocrat's Otherworldly Adventure Serving Gods Who Go Too Far.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "My Home Hero",
        image: "../images/My Home Hero.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "My Clueless First Friend",
        image: "../images/My Clueless First Friend.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Mobile Suit Gundam: The Witch from Mercury",
        image: "../images/Mobile Suit Gundam The Witch from Mercury.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
	    {
        title: "Natsume's Book of Friends Season 3",
        image: "../images/Natsume's Book of Friends Season 3.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
		    {
        title: "In/Spectre - Season 2",
        image: "../images/InSpectre - Season 2.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Sunday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
		    {
        title: "Anime Title 4",
        image: "../images/overlord.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Friday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
		    {
        title: "Anime Title 4",
        image: "../images/overlord.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Friday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-17T11:30:00",
        score: 8.5,
        currentEpisode: 4,
        totalEpisodes: 12,
    },
		    {
        title: "Anime Title tester",
        image: "../images/overlord.jpg",
        synopsis: "Synopsis for Anime 4",
        votes: 0,
        airingDay: "Friday",
        duration: 6,
        startDate: "2023-04-01",
        airTime: "2023-05-05T15:53:00",
        score: 8.5,
        currentEpisode: 12,
        totalEpisodes: 12,
    },
];
